### PR TITLE
More Types

### PR DESCRIPTION
**Pull request by Hydrocharged**
Implemented DECIMAL, TIME, ENUM, and SET, along with missing type aliases.

Depends on https://github.com/liquidata-inc/go-mysql-server/pull/83

### CODE REVIEW

**Comment by Hydrocharged** [comment]
Which bats tests are still skipped that I need to unskip?

**Comment by timsehn** [comment]
For instance:
https://github.com/liquidata-inc/dolt/blob/master/bats/types.bats#L318

**Comment by Hydrocharged** [comment]
I've unskipped that one
https://github.com/liquidata-inc/dolt/pull/557/files#diff-7eeb754e522ac1592981b96487e3a8c2L319

**Comment by Hydrocharged** [comment]
@zachmu two PRs to choose from, pick the one that you're happiest with lol
https://github.com/liquidata-inc/dolt/pull/572

**Comment by Hydrocharged** [comment]
This PR has been fully replaced by https://github.com/liquidata-inc/dolt/pull/572, thus I'm closing this one.

**Pull request closed without merging**
