### PR TITLE
fix panic

### PR DESCRIPTION
**Pull request by andrew-wm-arthur**
fix of [630](https://github.com/liquidata-inc/dolt/issues/630)

### CODE REVIEW

**Comment by andrew-wm-arthur** [comment]
BATS incoming

**Comment by timsehn** [comment]
No bats? How would we have caught this?

**Comment by andrew-wm-arthur** [comment]
The issue I haven't resolved is how NULL values were written to the non-primary key tuples. 
I haven't been able to reproduce this with any bats test.

**Comment by timsehn** [comment]
NULL values can be in non-primary keys. I don't understand.

--Tim

**Comment by andrew-wm-arthur** [comment]
We don't story NULL values, tho. They don't get written to the noms tuple. This panic was from a noms NULL value being compared to a non-existant column in the other side of the diff.

**Comment by timsehn** [comment]
Weird. Here's what I did:

1. Run that import script to create the table with an all text schema.
2. Inspect the schema looking for better types
3. For columns I wanted different type I dropped the column, added with a
new type, same name different tag
4. Run the import again to add the values back to the column

**Comment by andrew-wm-arthur** [comment]
OK I'm going to merge this. I'll open another issue to investigate the NULLS being written

**Comment by andrew-wm-arthur** [comment]
https://github.com/liquidata-inc/dolt/issues/659

**Pull request merged**
